"""is_admin default value

Revision ID: 3e537db6be23
Revises: d659c3f374ab
Create Date: 2020-09-12 12:11:28.198167

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3e537db6be23'
down_revision = 'd659c3f374ab'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
