"""Add users table and superuser

Revision ID: d659c3f374ab
Revises: 
Create Date: 2020-09-10 22:10:10.138589

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
from core.users.auth import get_password_hash

revision = 'd659c3f374ab'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(), nullable=True),
    sa.Column('password', sa.String(), nullable=True),
    sa.Column('first_name', sa.String(), nullable=True),
    sa.Column('last_name', sa.String(), nullable=True),
    sa.Column('is_admin', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
    admin_info = {
        'username': 'admin',
        'password': get_password_hash('admin'),
        'first_name': 'John',
        'last_name': 'Levis',
        'is_admin': 1
    }

    op.execute("INSERT INTO users (username, password, first_name, last_name, is_admin) "
               "values ('{username}','{password}','{first_name}','{last_name}','{is_admin}')"
               .format(**admin_info))


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users')
    # ### end Alembic commands ###
